### ISSUE TITLE
Error sending cash: Witness for note commitment is null

### ISSUE THREAD

**Issue by Tejeni** [HorizenOfficial/zencash-swing-wallet-ui#165]
I am unable to send zen from private address to a transparent address.  I get this following error message and I am unable to send funds from the private address.  I reindexed block chain (took 3 days) and also rescanned block chain and funds are still stuck.  Also upgraded to latest version of 0.90.2. swing wallet so far no luck sending.  I have been able to send smaller amounts of zen from private address but last remaining amount appears to be stuck.
<img width="1139" alt="Screen Shot 2020-11-08 at 10 59 22 PM" src="https://user-images.githubusercontent.com/20000442/98501959-5a078800-2216-11eb-8f12-96c270b66642.png">

**Comment by angievi** [comment]
Hello @Tejeni , in order to debug this issue it would be useful for us to have your wallet.dat file.
If you do not have any sensitive information stored in the wallet transaction history, and are willing to share the wallet file with us, please create a ticket at: https://horizenofficial.atlassian.net/servicedesk/customer/portals. We will provide you with further instructions on how to proceed with this on the help desk, please also refer the github issue.

We will compensate you for the zen you are unable to spend if you provide the wallet.dat file with us.

**Comment by Tejeni** [comment]
I am aware of the sensitivity of the wallet.dat file.  I don't wish to upload that particular file to you from my swing wallet.  I do understand the severity of this potential loss of funds error.  I really want to assist you with solving this issue.  Please let me add that this private address was imported into my my swing wallet from a secure node that was using the private address for staking a zen node originally.  I also tried on the zen node to send the zen out of original wallet on the zen node with this private address using the zen-cli z_sendmany command which also failed after multiple attempts to transfer funds.  

If you wish, since there is a trivial amount of zen on this private address I would be willing to pass you the private key to the private address for you to further research this issue if you want to import the private address with the problem in your your swing wallet.  Since this issue appears to be reproducible across two wallet.dat files, I willing to bet you can replicate the issue.  Otherwise, If need be, I would consider providing you a copy the zen node wallet.dat file from the zen node if you think that the file is truly needed.  Unfortunately, I would not be comfortable sharing the wallet.dat file from my current swing wallet due to the presence of the private keys of address I regularly use for zen transfers.

**Comment by SpencerWhetstone-Horizen** [comment]
@Tejeni 
Please perform the following:
The only sure way to fix the issue is
1. export z-address private key of the address with the unspendable note
2. stop swing
3. take backup cd $HOME/Library/Applicaction\ Support/Zen && mkdir backup && mv {blocks,chainstate,wallet.dat} backups
4. start zend with -connect= to force block height 0: in 2nd terminal window zend -connect=127.0.0.1:12345
5. wait for start, then import z-addr PK: zen-cli z_importkey $key_from_step_1
6. stop zend, zen-cli stop, start swing normally and wait until fully synced
7. Send the remaining z_addr balance to an address of choice, it should be spendable now
8. stop swing, move back backup folders: cd $HOME/Library/Applicaction\ Support/Zen && rm {blocks,chainstate,wallet.dat} && mv backups/{blocks,chainstate,wallet.dat} .
9. start swing again, after syncing last couple of blocks all should be good

Please remember that absolute paths to zend/zen-cli have to be provided.

I am a little pressed for time this week, but I will try to be available to get you through this without sending us your .dat file.

Regards,

Spencer
Help Desk Volunteer

**Comment by Tejeni** [comment]
You can close this issue.  Your solution worked.
