### ISSUE TITLE
How can I get into the ZENCashWallet?

### ISSUE THREAD

**Issue by Jgapoff** [HorizenOfficial/zencash-swing-wallet-ui#171]
When I open it I get this error message that is attached. Anyway I can get into the wallet, for some reason it is the only wallet that I don't have private keys written down for, so I need to get into it to recover the coins. 
![Screen Shot 2021-04-17 at 1 44 13 PM](https://user-images.githubusercontent.com/82725407/115122246-e320a900-9f84-11eb-8922-429b5b3d98cf.jpeg)

**Comment by cronicc** [comment]
This issue is usually caused by antivirus software detecting zend and zen-cli as potentially unwanted software. Please install the latest version of Swing wallet and make sure no antivirus software has removed zend and zen-cli (add exceptions if files are being removed).

Please also take note of Swing being [deprecated](https://github.com/HorizenOfficial/zencash-swing-wallet-ui#deprecation-notice).

If the issue persists feel free to reopen it.
