### ISSUE TITLE
ZEN Cash Wallet error to send funds

### ISSUE THREAD

**Issue by jmarcosoliver** [HorizenOfficial/zencash-swing-wallet-ui#189]
please...anyone already know how to solve this problem?
I click on Send put the wallet and after on Confirm... After some minutes, show this message:  https://prnt.sc/f-_1yQtjbDDs

minute 16"
https://youtu.be/funzQFAA354

SO windows 10
Sphere last version

thanks for any help

**Comment by psyraxaus** [comment]
Sphere isn't this wallet, but my answer still applies. 

Unfortunately the issue with the faucet payments is because of the many smaller inbound transactions when you try to send a larger amount of zen consisting of the smaller inbound transactions the outbound transaction becomes oversized

This means that the outbound transaction is using too many inputs (UXTOs) and is creating an oversize transaction

You will need to try sending a smaller amount.  Try sending half of what you were trying to send, if that don't work, please try sending half of the half until it does send

Think of it is like this, if you have 1000 inbound transactions of 0.01 zen, you would have a total of 10 zen.  

You would not be able to send this 10 zen amount because if you tried to send the whole amount the transaction would consume all the available inbound transactions and cause the outbound transaction to be oversize. 

You would need to split up the outbound transaction into small amounts.

**Comment by jmarcosoliver** [comment]
nice... it works !!!
thank u so much
![success](https://github.com/HorizenOfficial/zencash-swing-wallet-ui/assets/48003032/e92c5d2b-32fd-4f80-b2d9-16687da784ca)
